name: build container image

on:
  push:
    branches:
    - release-**
    tags:
    - 'v[0-9].[0-9]+.[0-9]+'

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  IMAGE_NAME: llaoj/kube-finder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image to ACR
        run: |
          SHA8=${GITHUB_SHA::8}
          GITHUB_REF=${GITHUB_REF#refs/*/}
          if [[ "$GITHUB_REF" == "release-"* ]]; then
            IMAGE=$REGISTRY/$IMAGE_NAME:${SHA8}-test
          else
            IMAGE=$REGISTRY/$IMAGE_NAME:$GITHUB_REF
          fi
          docker build -f deploy/Dockerfile -t $IMAGE .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
          docker push $IMAGE
