name: build container image

on:
  push:
    branch:
    - main

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  IMAGE_NAME: llaoj/kube-finder

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   SHA8: ${GITHUB_SHA::8}
    steps:

      - uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=image::$REGISTRY/$IMAGE_NAME"

      - name: Build and push image to ACR
        run: |
          docker build -f deploy/Dockerfile -t ${{ steps.vars.outputs.image }} .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
          docker push ${{ steps.vars.outputs.image }}
